### ISSUE TITLE
trunk-action installed old version when using latest

### ISSUE THREAD

**Issue by spanishpear** [jetli/trunk-action#25]
Hey!

Reporting this here - it hasn't occurred again but reporting anyways...

I have trunk-action on a build, and yesterday it seems to have downloaded trunk `0.10` as the latest version
![image](https://user-images.githubusercontent.com/27941681/207051804-bf41e03b-0d47-4d41-bd89-f72b69e14559.png)

https://github.com/SpanishPear/mipsy_web/actions/runs/3671124808/jobs/6206113585

Which shouldn't happen as i understand it!

**Comment by jetli** [comment]
You can upgrade trunk action to v0.2.0 anyway. The version of trunk is determined by GitHub rest api.

**Comment by spanishpear** [comment]
ooh thanks for the heads up, will update. 

Huh guess github had a freak out then - will close :D
