### ISSUE TITLE
wasm32 not included?

### ISSUE THREAD

**Issue by nuzzles** [jetli/trunk-action#27]
Example: https://github.com/rustgameexperts/bevy-shell-template/actions/runs/3946427847/jobs/6754179100

Happening now - For some reason the trunk action doesn't have wasm32? I can't remember needing to set up the toolchain before. This is new behavior AFAIK.

```
   Compiling serde v1.0.143
   Compiling cfg-if v1.0.0
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`
```

**Comment by jetli** [comment]
I think you need to setup toolchain by other GitHub action like yew: https://github.com/yewstack/yew/blob/c5ffe601f2822c5e2a4fcd08aa502c7f63775354/.github/workflows/publish-examples.yml#L20

**Comment by nuzzles** [comment]
Interestingly enough, I didn't. Still unsure why this failed, but it works now.
