### ISSUE TITLE
"Node.js 16 actions are deprecated" warning

### ISSUE THREAD

**Issue by ydirson** [jetli/trunk-action#30]
When using v0.4.0 we get the following warning for every wokflow run:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: jetli/trunk-action@v0.4.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by jetli** [comment]
fixed, upgrade to node20
